# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matMultArma <- function(A, B) {
    .Call(`_wSIR_matMultArma`, A, B)
}

computeRandZ <- function(X) {
    .Call(`_wSIR_computeRandZ`, X)
}

fastEigen <- function(S) {
    .Call(`_wSIR_fastEigen`, S)
}

subsetLowerTri <- function(m) {
    .Call(`_wSIR_subsetLowerTri`, m)
}

rank <- function(x) {
    .Call(`_wSIR_rank`, x)
}

spearman_correlation <- function(x, y) {
    .Call(`_wSIR_spearman_correlation`, x, y)
}

